name: Code Review CI

on: 
  push:
  pull_request:

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for diff analysis
      
      - name: Run code review
        run: |
          curl --request POST \
            --url https://api.devin.ai/v1/sessions \
            --header 'Authorization: Bearer <token>' \
            --header 'Content-Type: application/json' \
            --data '{
              "prompt": "!eval_rules -- Follow the CI/CD Guidelines Assessment Playbook in devin/devin_playbook.md to evaluate code changes against .windsurf/rules/ guidelines. Analyze only the diff (not entire repo) and report violations in priority order: security vulnerabilities, production stability risks, data integrity issues, performance impacts, maintainability concerns, code consistency.",
              "idempotent": true
            }'

